services:
  - type: web
    name: suspicious-conversation-analyzer
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python -c "import nltk; nltk.download('vader_lexicon')"
    startCommand: streamlit run main.py --server.address=0.0.0.0 --server.port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROQ_API_KEY
        sync: false
